"""adding unique constraint in products in models.py

Revision ID: f1fe95ac9ac7
Revises: 0759cc0d06af
Create Date: 2026-02-25 11:27:49.892637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fe95ac9ac7'
down_revision: Union[str, Sequence[str], None] = '0759cc0d06af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_customer_prooduct_uc', 'products', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_customer_prooduct_uc', 'products', type_='unique')
    # ### end Alembic commands ###
